name: 'Install Dependencies'
description: 'Reusable steps to use pnpm and install dependencies'
inputs:
  node-version:
    description: NodeJS Version
    required: true

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: |
          ${{ github.workspace }}/pnpm-lock.yaml

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile