name: Build and Test

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  # merge_group:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [auto_merge_enabled, ready_for_review]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: pnpm install
        uses: './.github/actions/install_deps'
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore prettier cache
        uses: actions/cache/restore@v4
        with:
          path: .cache/prettier
          key: prettier-main-cache
      - name: Format
        id: format
        run: pnpm format:ci
        continue-on-error: true
      - name: Please run `pnpm format`
        if: steps.format.outcome == 'failure'
        run: |
          echo "::error :: Please run pnpm format or Format action on your Pull Request"
          exit 1

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    env:
      SKIP_ENV_VALIDATION: 1

    steps:
      - uses: actions/checkout@v4
      - name: pnpm install
        uses: './.github/actions/install_deps'
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        id: 'lint'
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: [format, lint]
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: pnpm install
        uses: './.github/actions/install_deps'
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        id: 'build'
        run: pnpm run build

